// Adversarial Stress Tests: Hotkey Event Queue & State Machine
// Stress-tests rapid toggle bursts at 15-20Hz, OS autorepeats, queue overflow limits, and micro-tap coalescing.
const { describe, it, beforeEach } = require('node:test');
const assert = require('node:assert');

// Mock electron in require.cache for headless Node.js test environment
const { MockBrowserWindow, MockClipboard, MockIPC, mockApp } = require('../helpers/mock-electron');

const electronMock = {
  app: {
    ...mockApp,
    requestSingleInstanceLock: () => false,
    on: () => {},
    whenReady: () => Promise.resolve(),
    setLoginItemSettings: () => {},
    quit: () => {},
  },
  BrowserWindow: MockBrowserWindow,
  clipboard: new MockClipboard(),
  ipcMain: new MockIPC(),
  screen: { getPrimaryDisplay: () => ({ workArea: { x: 0, y: 0, width: 1920, height: 1080 } }) },
  shell: { openExternal: () => {}, openPath: () => {} },
  globalShortcut: { register: () => true, unregisterAll: () => {} },
  session: { defaultSession: { webRequest: { onHeadersReceived: () => {} } } },
  MessageChannelMain: class { constructor() { this.port1 = {}; this.port2 = {}; } },
};

require.cache[require.resolve('electron')] = {
  id: require.resolve('electron'),
  filename: require.resolve('electron'),
  loaded: true,
  exports: electronMock,
};

const { HotkeyStateMachine } = require('../../src/main.js');

describe('Adversarial Hotkey Event Queue Stress Tests', () => {
  it('ADV-HOTKEY-01: handles 50 rapid hotkey toggles at 15-20Hz with 0 dropped events', () => {
    const fsm = new HotkeyStateMachine({ maxQueueSize: 100 });

    // Initial utterance starts and enters PROCESSING
    fsm.handleEvent('KEY_DOWN', 'ptt');
    fsm.handleEvent('KEY_UP', 'ptt');
    assert.strictEqual(fsm.state, 'PROCESSING');

    // Simulate 50 rapid toggle inputs arriving at 20Hz (50ms interval)
    const toggleCount = 50;
    const baseTime = Date.now();
    for (let i = 0; i < toggleCount; i++) {
      const eventTime = baseTime + (i * 50);
      const res = fsm.handleEvent('KEY_DOWN', 'ptt');
      assert.strictEqual(res.action, 'enqueued', `Toggle ${i + 1} must be enqueued`);
      assert.strictEqual(res.depth, i + 1);
    }

    assert.strictEqual(fsm.state, 'QUEUED');
    assert.strictEqual(fsm.queue.length, 50, 'Queue must hold all 50 events without loss');
    assert.strictEqual(fsm.droppedEvents, 0, 'Dropped events must be exactly 0 under 50 toggles');
  });

  it('ADV-HOTKEY-02: suppresses 100 continuous OS keyboard autorepeats during active hold', () => {
    // 1. FSM level verification
    const fsm = new HotkeyStateMachine();
    const initial = fsm.handleEvent('KEY_DOWN', 'ptt');
    assert.strictEqual(initial.action, 'capture-start');
    assert.strictEqual(fsm.state, 'LISTENING_PTT');

    // 100 repeated KEY_DOWN events generated by Windows OS keyboard repeat
    let ignoredAtFsm = 0;
    for (let i = 0; i < 100; i++) {
      const res = fsm.handleEvent('KEY_DOWN', 'ptt');
      if (res.action === 'ignored') ignoredAtFsm++;
    }

    assert.strictEqual(ignoredAtFsm, 100, 'All 100 autorepeat events must be ignored by FSM');
    assert.strictEqual(fsm.state, 'LISTENING_PTT', 'State must remain LISTENING_PTT');
    assert.strictEqual(fsm.queue.length, 0, 'Autorepeat events must never be queued');

    // 2. OS hook level verification (heldKeys set deduplication)
    const heldKeys = new Set();
    const pttKeycode = 56; // Alt or Win
    let dispatchedEvents = 0;

    function simulateOsKeyDown(keycode) {
      if (heldKeys.has(keycode)) return false;
      heldKeys.add(keycode);
      dispatchedEvents++;
      return true;
    }

    function simulateOsKeyUp(keycode) {
      heldKeys.delete(keycode);
    }

    // First keypress
    const firstPressAccepted = simulateOsKeyDown(pttKeycode);
    assert.strictEqual(firstPressAccepted, true);
    assert.strictEqual(dispatchedEvents, 1);

    // 100 OS autorepeats while held
    let suppressedCount = 0;
    for (let i = 0; i < 100; i++) {
      const accepted = simulateOsKeyDown(pttKeycode);
      if (!accepted) suppressedCount++;
    }

    assert.strictEqual(suppressedCount, 100, 'All 100 OS autorepeat messages must be suppressed');
    assert.strictEqual(dispatchedEvents, 1, 'Only the initial keypress must dispatch');

    // Release key
    simulateOsKeyUp(pttKeycode);
    assert.strictEqual(heldKeys.has(pttKeycode), false);
  });

  it('ADV-HOTKEY-03: enforces strict bounds and drops events when queue exceeds maxQueueSize', () => {
    const maxCapacity = 50;
    const fsm = new HotkeyStateMachine({ maxQueueSize: maxCapacity });

    // Transition to PROCESSING
    fsm.handleEvent('KEY_DOWN', 'ptt');
    fsm.handleEvent('KEY_UP', 'ptt');
    assert.strictEqual(fsm.state, 'PROCESSING');

    // Fill queue to max capacity
    for (let i = 0; i < maxCapacity; i++) {
      const res = fsm.handleEvent('KEY_DOWN', 'ptt');
      assert.strictEqual(res.action, 'enqueued');
    }
    assert.strictEqual(fsm.queue.length, maxCapacity);
    assert.strictEqual(fsm.droppedEvents, 0);

    // Flood with 25 excess events
    const overflowCount = 25;
    for (let i = 0; i < overflowCount; i++) {
      const res = fsm.handleEvent('KEY_DOWN', 'ptt');
      assert.strictEqual(res.action, 'dropped', `Overflow event ${i + 1} must be dropped`);
      assert.strictEqual(res.queueLength, maxCapacity);
    }

    assert.strictEqual(fsm.queue.length, maxCapacity, 'Queue must not exceed maxQueueSize');
    assert.strictEqual(fsm.droppedEvents, overflowCount, 'Dropped counter must match overflow count');
  });

  it('ADV-HOTKEY-04: coalesces sub-80ms micro-taps and preserves intentional taps >=80ms', () => {
    const fsm = new HotkeyStateMachine();
    fsm.handleEvent('KEY_DOWN', 'ptt');
    fsm.handleEvent('KEY_UP', 'ptt'); // PROCESSING

    const now = Date.now();

    // 1. Accidental micro-tap: 45ms duration (should coalesce)
    fsm.queue.push({ type: 'KEY_DOWN', key: 'ptt', timestamp: now });
    fsm.queue.push({ type: 'KEY_UP', key: 'ptt', timestamp: now + 45 });

    // 2. Intentional short dictation tap: 120ms duration (should preserve)
    fsm.queue.push({ type: 'KEY_DOWN', key: 'ptt', timestamp: now + 100 });
    fsm.queue.push({ type: 'KEY_UP', key: 'ptt', timestamp: now + 220 });

    assert.strictEqual(fsm.queue.length, 4);

    // Calling completeProcessing should drain the 45ms micro-tap and start the 120ms tap
    const outcome = fsm.completeProcessing();
    assert.strictEqual(outcome.action, 'capture-start');
    assert.strictEqual(outcome.nextEvent.key, 'ptt');
    assert.strictEqual(fsm.state, 'LISTENING_PTT');
    // Remaining in queue: the KEY_UP for the 120ms tap
    assert.strictEqual(fsm.queue.length, 1);
  });

  it('ADV-HOTKEY-05: handles high-frequency alternating mode thrashing without deadlock', () => {
    const fsm = new HotkeyStateMachine({ maxQueueSize: 60 });
    fsm.handleEvent('KEY_DOWN', 'ptt');
    fsm.handleEvent('KEY_UP', 'ptt'); // PROCESSING

    // Rapid thrashing between PTT and handsfree toggles (30 alternating events)
    for (let i = 0; i < 30; i++) {
      const key = i % 2 === 0 ? 'ptt' : 'handsfree';
      const type = i % 4 < 2 ? 'KEY_DOWN' : 'KEY_UP';
      fsm.handleEvent(type, key);
    }

    assert.strictEqual(fsm.queue.length, 30);
    assert.strictEqual(fsm.state, 'QUEUED');

    // Drain all events step by step to verify clean return to IDLE
    let steps = 0;
    while (fsm.queue.length > 0 && steps < 50) {
      steps++;
      fsm.completeProcessing();
      fsm.state = 'PROCESSING';
    }

    const final = fsm.completeProcessing();
    assert.strictEqual(final.action, 'idle');
    assert.strictEqual(fsm.state, 'IDLE');
  });
});
